Repository w3c/sustainableweb-wsg, pull requests merged in 2025-04, with the labels that each got.

#41 Changelog & Minor Fixes
  IG-CONTRIBUTING.md
  README.md
  glance.html
  index.html
  intro.html
  policies.html
  star.html
  star.json
  test-suite/BSPM01-6.html
  test-suite/BSPM12-3.html
  test-suite/BSPM23-1.html
  test-suite/BSPM27-1.html
  test-suite/BSPM28-3.html
  test-suite/HIS06-4.html
  test-suite/HIS12-5.html
  test-suite/WD14-4.html
Labels: enhancement

#48 fix: fix typo
  guidelines.json
  index.html
  quickref.html
Labels: technical

#49 STAR Hotfix
  index.html
Labels: technical

#52 Minor updates
  glance.html
  guidelines.json
  index.html
  intro.html
  policies.html
  quickref.html
  star.html
  star.json
Labels: technical

#56 Filtering, SCs, & More
  README.md
  checklist.pages
  checklist.pdf
  glance.html
  guidelines.json
  index.html
  quickref.html
  star.html
  star.json
  test-suite/HIS01-6.html
  test-suite/WD09-2.html
Labels: enhancement, taskforce-all

#58 Filter Updates
  index.html
Labels: technical

#59 Minor Fixes & Updates
  README.md
  glance.html
  guidelines.json
  index.html
  intro.html
  policies.html
  quickref.html
  star.html
  star.json
Labels: technical

#60 JS Optimizations & Tag Updates
  glance.html
  guidelines.json
  index.html
  intro.html
  policies.html
  quickref.html
  star.html
Labels: technical
